[package]
name = "ct_df"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "df ~ (ctutils) display file system information"
repository = "https://atomgit.com/openeuler/syskits/src/branch/master/crates/commands/cp"

[lib]
path = "src/df.rs"

[dependencies]
sys-locale = { workspace = true }
rust-i18n = { workspace = true }
clap = { workspace = true }
ctcore = { workspace = true, features = ["libc", "fsext"] }
ctengine = { workspace = true, optional = true }
ctpipeline = { workspace = true, optional = true }
ctsig = { workspace = true, optional = true }

unicode-width = { workspace = true }
[features]
feat_typed_cmds = ["ctengine", "ctpipeline", "ctsig"]

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "df"
path = "src/main.rs"
