[package]
name = "cmd_tac"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native tac command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ct_tac = { path = "../../commands/tac" }
ctcore = { workspace = true }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
