[package]
name = "cmd_retry"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "DataCommand: retry — retry expression on runtime failures"

[dependencies]
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ctengine = { workspace = true }
ctdsl = { workspace = true }
