[package]
name = "cmd_dircolors"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native dircolors command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ctcore = { workspace = true }
ct_dircolors = { path = "../../commands/dircolors" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
