[package]
name = "cmd_hashsum"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native hashsum command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ctcore = { workspace = true }
ct_hashsum = { path = "../../commands/hashsum" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
