[package]
name = "cmd_fmt"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native fmt command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ctcore = { workspace = true }
ct_fmt = { path = "../../commands/fmt" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
