[package]
name = "cmd_nproc"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Native nproc data command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ct_nproc = { package = "ct_nproc", path = "../../commands/nproc" }
