[package]
name = "cmd_pr"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Structured data command for pr"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[lib]
path = "src/lib.rs"

[dependencies]
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ct_pr = { package = "ct_pr", path = "../../commands/pr" }

[dev-dependencies]
tempfile = { workspace = true }
