[package]
name = "cmd_env"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native env command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ct_env = { path = "../../commands/env" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
