[package]
name = "cmd_wc"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Native wc data command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ct_wc = { package = "ct_wc", path = "../../commands/wc" }
ctcore = { workspace = true }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
