[package]
name = "cmd_seq"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native seq command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ct_seq = { path = "../../commands/seq" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
