[package]
name = "cmd_od"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native od command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ctcore = { workspace = true }
ct_od = { path = "../../commands/od" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
