[package]
name = "cmd_base64"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Structured data command for base64"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[lib]
path = "src/lib.rs"

[dependencies]
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ct_base64 = { package = "ct_base64", path = "../../commands/base64" }

[dev-dependencies]
tempfile = { workspace = true }
