[package]
name = "cmd_factor"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native factor command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ctcore = { workspace = true }
ct_factor = { path = "../../commands/factor" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
