[package]
name = "cmd_hostid"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native hostid command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
ct_hostid = { path = "../../commands/hostid" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
