/*
 * Copyright(c) 2022-2025 China Telecom Cloud Technologies Co., Ltd. All rights reserved.
 *  syskits is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL V2.
 * You may obtain a copy of Mulan PSL v2 at: http://license.coscl.org.cn/MulanPSL2.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

//! `ct_shell_init` — syskits shell 初始化脚本生成器（M2）。
//!
//! 用途：
//! ```text
//! eval "$(syskits shell-init bash)"   # 在 ~/.bashrc 中添加
//! eval "$(syskits shell-init zsh)"    # 在 ~/.zshrc 中添加
//! syskits shell-init fish | source    # 在 fish config 中添加
//! ```
//!
//! 通过 `--no-completion` 可跳过 completion 脚本注入。

extern crate rust_i18n;
rust_i18n::i18n!("locales", fallback = "en-US");

use clap::{Arg, ArgAction, Command, crate_version};
use ctcore::Tool;
use ctcore::ct_error::CTResult;
use std::ffi::OsString;
use std::io::{self, Write};
use sys_locale::get_locale;

/// 支持的 shell 类型
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Bash,
    Zsh,
    Fish,
}

impl ShellKind {
    fn from_str(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "bash" => Some(Self::Bash),
            "zsh" => Some(Self::Zsh),
            "fish" => Some(Self::Fish),
            _ => None,
        }
    }
}

/// `shell-init` 工具入口 struct
#[derive(Default)]
pub struct ShellInit;

impl Tool for ShellInit {
    fn name(&self) -> &'static str {
        "shell-init"
    }

    fn command(&self) -> Command {
        shell_init_app()
    }

    fn execute(&self, args: &[OsString]) -> CTResult<()> {
        shell_init_main(args.iter().cloned())
    }
}

/// 构建 clap 命令定义
pub fn shell_init_app() -> Command {
    let lang = get_locale().unwrap_or_else(|| "en-US".to_string());
    rust_i18n::set_locale(&lang);

    Command::new(ctcore::ct_util_name())
        .version(crate_version!())
        .about("Generate shell initialization scripts for syskits integration")
        .override_usage("shell-init <SHELL> [OPTIONS]")
        .arg(
            Arg::new("shell")
                .value_name("SHELL")
                .required(true)
                .help("Target shell: bash | zsh | fish"),
        )
        .arg(
            Arg::new("no-completion")
                .long("no-completion")
                .action(ArgAction::SetTrue)
                .help("Skip shell completion script injection"),
        )
}

/// 执行 shell-init，将脚本输出到 stdout
pub fn shell_init_main(args: impl ctcore::Args) -> CTResult<()> {
    let matches = shell_init_app().try_get_matches_from(args)?;
    let shell_str = matches.get_one::<String>("shell").unwrap();
    let no_completion = matches.get_flag("no-completion");

    let kind = ShellKind::from_str(shell_str).ok_or_else(|| {
        ctcore::ct_error::CtSimpleError::new(
            1,
            format!("shell-init: unsupported shell `{shell_str}`; supported: bash, zsh, fish"),
        )
    })?;

    let script = match kind {
        ShellKind::Bash => bash::generate(no_completion),
        ShellKind::Zsh => zsh::generate(no_completion),
        ShellKind::Fish => fish::generate(no_completion),
    };

    let stdout = io::stdout();
    let mut out = stdout.lock();
    out.write_all(script.as_bytes()).map_err(|e| {
        ctcore::ct_error::CtSimpleError::new(1, format!("shell-init: write error: {e}"))
    })?;

    Ok(())
}

// ─────────────────────────────────────────────
// Bash init 脚本
// ─────────────────────────────────────────────
pub mod bash {
    /// 生成 bash 初始化脚本
    pub fn generate(no_completion: bool) -> String {
        let mut s = String::with_capacity(512);
        s.push_str("# Generated by syskits shell-init bash\n");
        s.push_str("# Add to ~/.bashrc:\n");
        s.push_str("#   eval \"$(syskits shell-init bash)\"\n");
        s.push('\n');
        s.push_str("export SYSKITS_SHELL=bash\n");
        s.push('\n');
        // data 管线别名
        s.push_str("# syskits data pipeline alias\n");
        s.push_str("alias skdata='syskits data'\n");
        // 外部命令桥接快捷方式
        s.push_str("alias skrun='syskits data run-external'\n");
        s.push('\n');
        // completion 注入（可选）
        if !no_completion {
            s.push_str("# shell completion\n");
            s.push_str("if command -v syskits &>/dev/null; then\n");
            s.push_str("  eval \"$(syskits completion syskits bash 2>/dev/null || true)\"\n");
            s.push_str("fi\n");
        }
        s
    }
}

// ─────────────────────────────────────────────
// Zsh init 脚本
// ─────────────────────────────────────────────
pub mod zsh {
    /// 生成 zsh 初始化脚本
    pub fn generate(no_completion: bool) -> String {
        let mut s = String::with_capacity(512);
        s.push_str("# Generated by syskits shell-init zsh\n");
        s.push_str("# Add to ~/.zshrc:\n");
        s.push_str("#   eval \"$(syskits shell-init zsh)\"\n");
        s.push('\n');
        s.push_str("export SYSKITS_SHELL=zsh\n");
        s.push('\n');
        // data 管线别名
        s.push_str("# syskits data pipeline alias\n");
        s.push_str("alias skdata='syskits data'\n");
        s.push_str("alias skrun='syskits data run-external'\n");
        s.push('\n');
        // completion 注入（可选）
        if !no_completion {
            s.push_str("# shell completion\n");
            s.push_str("if (( $+commands[syskits] )); then\n");
            s.push_str("  autoload -Uz compinit && compinit\n");
            s.push_str("  eval \"$(syskits completion syskits zsh 2>/dev/null || true)\"\n");
            s.push_str("fi\n");
        }
        s
    }
}

// ─────────────────────────────────────────────
// Fish init 脚本
// ─────────────────────────────────────────────
pub mod fish {
    /// 生成 fish 初始化脚本
    pub fn generate(no_completion: bool) -> String {
        let mut s = String::with_capacity(512);
        s.push_str("# Generated by syskits shell-init fish\n");
        s.push_str("# Add to ~/.config/fish/config.fish:\n");
        s.push_str("#   syskits shell-init fish | source\n");
        s.push('\n');
        s.push_str("set -x SYSKITS_SHELL fish\n");
        s.push('\n');
        // data 管线别名
        s.push_str("# syskits data pipeline alias\n");
        s.push_str("alias skdata 'syskits data'\n");
        s.push_str("alias skrun 'syskits data run-external'\n");
        s.push('\n');
        // completion 注入（可选）
        if !no_completion {
            s.push_str("# shell completion\n");
            s.push_str("if type -q syskits\n");
            s.push_str("  syskits completion syskits fish 2>/dev/null | source\n");
            s.push_str("end\n");
        }
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── bash ──────────────────────────────────
    #[test]
    fn test_bash_contains_env() {
        let s = bash::generate(false);
        assert!(s.contains("SYSKITS_SHELL=bash"), "got: {s}");
    }

    #[test]
    fn test_bash_contains_skdata_alias() {
        let s = bash::generate(false);
        assert!(s.contains("alias skdata="), "got: {s}");
    }

    #[test]
    fn test_bash_completion_included_by_default() {
        let s = bash::generate(false);
        assert!(s.contains("syskits completion"), "got: {s}");
    }

    #[test]
    fn test_bash_no_completion_flag() {
        let s = bash::generate(true);
        assert!(!s.contains("syskits completion"), "got: {s}");
    }

    // ── zsh ───────────────────────────────────
    #[test]
    fn test_zsh_contains_env() {
        let s = zsh::generate(false);
        assert!(s.contains("SYSKITS_SHELL=zsh"), "got: {s}");
    }

    #[test]
    fn test_zsh_contains_skdata_alias() {
        let s = zsh::generate(false);
        assert!(s.contains("alias skdata="), "got: {s}");
    }

    #[test]
    fn test_zsh_completion_included_by_default() {
        let s = zsh::generate(false);
        assert!(s.contains("syskits completion"), "got: {s}");
    }

    #[test]
    fn test_zsh_no_completion_flag() {
        let s = zsh::generate(true);
        assert!(!s.contains("syskits completion"), "got: {s}");
    }

    // ── fish ──────────────────────────────────
    #[test]
    fn test_fish_contains_env() {
        let s = fish::generate(false);
        assert!(s.contains("SYSKITS_SHELL fish"), "got: {s}");
    }

    #[test]
    fn test_fish_contains_skdata_alias() {
        let s = fish::generate(false);
        assert!(s.contains("alias skdata "), "got: {s}");
    }

    #[test]
    fn test_fish_completion_included_by_default() {
        let s = fish::generate(false);
        assert!(s.contains("syskits completion"), "got: {s}");
    }

    #[test]
    fn test_fish_no_completion_flag() {
        let s = fish::generate(true);
        assert!(!s.contains("syskits completion"), "got: {s}");
    }

    // ── ShellKind 解析 ────────────────────────
    #[test]
    fn test_shell_kind_from_str() {
        assert_eq!(ShellKind::from_str("bash"), Some(ShellKind::Bash));
        assert_eq!(ShellKind::from_str("zsh"), Some(ShellKind::Zsh));
        assert_eq!(ShellKind::from_str("fish"), Some(ShellKind::Fish));
        assert_eq!(ShellKind::from_str("BASH"), Some(ShellKind::Bash));
        assert_eq!(ShellKind::from_str("PowerShell"), None);
        assert_eq!(ShellKind::from_str(""), None);
    }
}
