[package]
name = "cmd_agg"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "DataCommand: agg — aggregate List<Record> or grouped rows"

[dependencies]
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ctengine = { workspace = true }
