[package]
name = "cmd_basenc"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Structured data command for basenc"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[lib]
path = "src/lib.rs"

[dependencies]
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ct_basenc = { package = "ct_basenc", path = "../../commands/basenc" }

[dev-dependencies]
tempfile = { workspace = true }
