[package]
name = "cmd_dirname"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native dirname command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ct_dirname = { path = "../../commands/dirname" }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
