[package]
name = "cmd_tr"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native tr command"
repository = "https://work.ctyun.cn/git/CTyunOS/syskits"

[dependencies]
ct_tr = { path = "../../commands/tr" }
ctcore = { workspace = true }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
