[package]
name = "cmd_uname"
version.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true

description = "Phase A native uname command"
repository = "https://atomgit.com/openeuler/syskits"

[dependencies]
clap = { workspace = true }
ctengine = { workspace = true }
ctpipeline = { workspace = true }
ctsig = { workspace = true }
ct_uname = { package = "ct_uname", path = "../../commands/uname" }
